language: cpp

compiler:
    - gcc
    - clang

env:
    global:
        - MONGO_REPO="http://repo.mongodb.com/apt/ubuntu"
        - REPO_TYPE="precise/mongodb-enterprise/2.6 multiverse"
        - SOURCES_LOC="/etc/apt/sources.list.d/mongodb-enterprise.list"
        - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
        - CMAKE_VERSION="cmake-3.1.3-Linux-x86_64"
        - CMAKE_BINARY="${CMAKE_VERSION}/bin/cmake"

    matrix:
        - CONFIG=Release
        - CONFIG=Debug

# Setup required repositories before installation
before_install:
    # Add the modern toolchain repositories (llvm repo depends on ubunut-toolchain-r + gcc)
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

    # Get the latest CMake
    - wget http://www.cmake.org/files/v3.1/${CMAKE_VERSION}.tar.gz

    # MongoDB Enterprise Edition 2.6
    - sudo apt-key adv --keyserver ${KEY_SERVER} --recv 7F0CEB10
    - echo "deb ${MONGO_REPO} ${REPO_TYPE}" | sudo tee ${SOURCES_LOC}

    # CMake
    - sudo add-apt-repository --yes ppa:kalakris/cmake

    # Update all the repositories
    - sudo apt-get update -qq

    # Mongo C Driver
    # TODO switch master (branch for current 1.3 dev) to r1.3 when released
    - git clone -b master https://github.com/mongodb/mongo-c-driver.git

install:
    # GCC
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; export CXX="g++-4.9"; export CC="gcc-4.9"; fi

    # Clang
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.6; export CXX="clang++-3.6"; export CC="clang-3.6"; fi

    # CMake
    - tar -zxvf ${CMAKE_VERSION}.tar.gz -C build

    # Install MongoDB Enterprise
    - sudo apt-get install mongodb-enterprise-server

    # Install CMake (Versions lower than 2.8.8 do not support object libraries)
    - sudo apt-get install cmake

    # Install Mongo C Driver
    - pushd mongo-c-driver; ./autogen.sh --enable-tests=no --enable-examples=no; make; sudo make install; popd;

before_script:
    - $CC --version
    - $CXX --version

    # Build the driver and the tests
    - cd build
    - ${CMAKE_BINARY} -DCMAKE_BUILD_TYPE=$CONFIG ..

script:
    - make -j3
    - make test
